// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/authService.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/authService.go -destination=internal/auth/mocks/mock_authService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "medassist/internal/auth/dto"
	model "medassist/internal/model"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// ChangePasswordLogged mocks base method.
func (m *MockAuthService) ChangePasswordLogged(changePasswordBothRequestDTO dto.ChangePasswordBothRequestDTO, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePasswordLogged", changePasswordBothRequestDTO, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePasswordLogged indicates an expected call of ChangePasswordLogged.
func (mr *MockAuthServiceMockRecorder) ChangePasswordLogged(changePasswordBothRequestDTO, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePasswordLogged", reflect.TypeOf((*MockAuthService)(nil).ChangePasswordLogged), changePasswordBothRequestDTO, id)
}

// ChangePasswordUnlogged mocks base method.
func (m *MockAuthService) ChangePasswordUnlogged(updatedPasswordByNewPassword dto.UpdatedPasswordByNewPassword, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePasswordUnlogged", updatedPasswordByNewPassword, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePasswordUnlogged indicates an expected call of ChangePasswordUnlogged.
func (mr *MockAuthServiceMockRecorder) ChangePasswordUnlogged(updatedPasswordByNewPassword, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePasswordUnlogged", reflect.TypeOf((*MockAuthService)(nil).ChangePasswordUnlogged), updatedPasswordByNewPassword, id)
}

// FirstLoginAdmin mocks base method.
func (m *MockAuthService) FirstLoginAdmin() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstLoginAdmin")
	ret0, _ := ret[0].(error)
	return ret0
}

// FirstLoginAdmin indicates an expected call of FirstLoginAdmin.
func (mr *MockAuthServiceMockRecorder) FirstLoginAdmin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstLoginAdmin", reflect.TypeOf((*MockAuthService)(nil).FirstLoginAdmin))
}

// LoginUser mocks base method.
func (m *MockAuthService) LoginUser(loginRequestDTO dto.LoginRequestDTO) (string, dto.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", loginRequestDTO)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(dto.AuthUser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockAuthServiceMockRecorder) LoginUser(loginRequestDTO any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockAuthService)(nil).LoginUser), loginRequestDTO)
}

// NurseRegister mocks base method.
func (m *MockAuthService) NurseRegister(nurseRequestDTO dto.NurseRegisterRequestDTO, files map[string][]*multipart.FileHeader) (model.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NurseRegister", nurseRequestDTO, files)
	ret0, _ := ret[0].(model.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NurseRegister indicates an expected call of NurseRegister.
func (mr *MockAuthServiceMockRecorder) NurseRegister(nurseRequestDTO, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NurseRegister", reflect.TypeOf((*MockAuthService)(nil).NurseRegister), nurseRequestDTO, files)
}

// ResetPassword mocks base method.
func (m *MockAuthService) ResetPassword(resetPasswordDTO dto.ResetPasswordDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", resetPasswordDTO)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAuthServiceMockRecorder) ResetPassword(resetPasswordDTO any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAuthService)(nil).ResetPassword), resetPasswordDTO)
}

// SendCodeToEmail mocks base method.
func (m *MockAuthService) SendCodeToEmail(emailAuthRequestDTO dto.EmailAuthRequestDTO) (dto.CodeResponseDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCodeToEmail", emailAuthRequestDTO)
	ret0, _ := ret[0].(dto.CodeResponseDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendCodeToEmail indicates an expected call of SendCodeToEmail.
func (mr *MockAuthServiceMockRecorder) SendCodeToEmail(emailAuthRequestDTO any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCodeToEmail", reflect.TypeOf((*MockAuthService)(nil).SendCodeToEmail), emailAuthRequestDTO)
}

// SendEmailForgotPassword mocks base method.
func (m *MockAuthService) SendEmailForgotPassword(email dto.ForgotPasswordRequestDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailForgotPassword", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailForgotPassword indicates an expected call of SendEmailForgotPassword.
func (mr *MockAuthServiceMockRecorder) SendEmailForgotPassword(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailForgotPassword", reflect.TypeOf((*MockAuthService)(nil).SendEmailForgotPassword), email)
}

// UserRegister mocks base method.
func (m *MockAuthService) UserRegister(registerRequestDTO dto.UserRegisterRequestDTO, files map[string][]*multipart.FileHeader) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRegister", registerRequestDTO, files)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserRegister indicates an expected call of UserRegister.
func (mr *MockAuthServiceMockRecorder) UserRegister(registerRequestDTO, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRegister", reflect.TypeOf((*MockAuthService)(nil).UserRegister), registerRequestDTO, files)
}

// ValidateToken mocks base method.
func (m *MockAuthService) ValidateToken(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthServiceMockRecorder) ValidateToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuthService)(nil).ValidateToken), token)
}

// ValidateUserCode mocks base method.
func (m *MockAuthService) ValidateUserCode(inputCodeDto dto.InputCodeDto) (string, dto.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserCode", inputCodeDto)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(dto.AuthUser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateUserCode indicates an expected call of ValidateUserCode.
func (mr *MockAuthServiceMockRecorder) ValidateUserCode(inputCodeDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserCode", reflect.TypeOf((*MockAuthService)(nil).ValidateUserCode), inputCodeDto)
}
