// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/reviewRepository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/reviewRepository.go -destination=internal/repository/mocks/mock_reviewRepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "medassist/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
	isgomock struct{}
}

// MockReviewRepositoryMockRecorder is the mock recorder for MockReviewRepository.
type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

// NewMockReviewRepository creates a new mock instance.
func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

// CreateReview mocks base method.
func (m *MockReviewRepository) CreateReview(review model.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReview", review)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReview indicates an expected call of CreateReview.
func (mr *MockReviewRepositoryMockRecorder) CreateReview(review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockReviewRepository)(nil).CreateReview), review)
}

// FindAllNurseReviews mocks base method.
func (m *MockReviewRepository) FindAllNurseReviews(nurseId string) ([]model.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllNurseReviews", nurseId)
	ret0, _ := ret[0].([]model.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllNurseReviews indicates an expected call of FindAllNurseReviews.
func (mr *MockReviewRepositoryMockRecorder) FindAllNurseReviews(nurseId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllNurseReviews", reflect.TypeOf((*MockReviewRepository)(nil).FindAllNurseReviews), nurseId)
}

// FindAllPatientReviews mocks base method.
func (m *MockReviewRepository) FindAllPatientReviews(patientId string) ([]model.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllPatientReviews", patientId)
	ret0, _ := ret[0].([]model.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllPatientReviews indicates an expected call of FindAllPatientReviews.
func (mr *MockReviewRepositoryMockRecorder) FindAllPatientReviews(patientId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllPatientReviews", reflect.TypeOf((*MockReviewRepository)(nil).FindAllPatientReviews), patientId)
}

// FindAverageRatingByNurseId mocks base method.
func (m *MockReviewRepository) FindAverageRatingByNurseId(nurseId string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAverageRatingByNurseId", nurseId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAverageRatingByNurseId indicates an expected call of FindAverageRatingByNurseId.
func (mr *MockReviewRepositoryMockRecorder) FindAverageRatingByNurseId(nurseId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAverageRatingByNurseId", reflect.TypeOf((*MockReviewRepository)(nil).FindAverageRatingByNurseId), nurseId)
}

// FindReviewByVisitId mocks base method.
func (m *MockReviewRepository) FindReviewByVisitId(visitId string) (model.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReviewByVisitId", visitId)
	ret0, _ := ret[0].(model.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindReviewByVisitId indicates an expected call of FindReviewByVisitId.
func (mr *MockReviewRepositoryMockRecorder) FindReviewByVisitId(visitId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReviewByVisitId", reflect.TypeOf((*MockReviewRepository)(nil).FindReviewByVisitId), visitId)
}
