// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/userRepository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/userRepository.go -destination=internal/repository/mocks/mock_userRepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	dto "medassist/internal/auth/dto"
	model "medassist/internal/model"
	dto0 "medassist/internal/nurse/dto"
	reflect "reflect"

	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gridfs "go.mongodb.org/mongo-driver/mongo/gridfs"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), user)
}

// DeleteUser mocks base method.
func (m *MockUserRepository) DeleteUser(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserRepositoryMockRecorder) DeleteUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserRepository)(nil).DeleteUser), id)
}

// DownloadFileByID mocks base method.
func (m *MockUserRepository) DownloadFileByID(fileID primitive.ObjectID) (*gridfs.DownloadStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFileByID", fileID)
	ret0, _ := ret[0].(*gridfs.DownloadStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFileByID indicates an expected call of DownloadFileByID.
func (mr *MockUserRepositoryMockRecorder) DownloadFileByID(fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFileByID", reflect.TypeOf((*MockUserRepository)(nil).DownloadFileByID), fileID)
}

// FindAllUsers mocks base method.
func (m *MockUserRepository) FindAllUsers() ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllUsers")
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllUsers indicates an expected call of FindAllUsers.
func (mr *MockUserRepositoryMockRecorder) FindAllUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllUsers", reflect.TypeOf((*MockUserRepository)(nil).FindAllUsers))
}

// FindAuthUserByID mocks base method.
func (m *MockUserRepository) FindAuthUserByID(id string) (dto.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAuthUserByID", id)
	ret0, _ := ret[0].(dto.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAuthUserByID indicates an expected call of FindAuthUserByID.
func (mr *MockUserRepositoryMockRecorder) FindAuthUserByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAuthUserByID", reflect.TypeOf((*MockUserRepository)(nil).FindAuthUserByID), id)
}

// FindFileByID mocks base method.
func (m *MockUserRepository) FindFileByID(ctx context.Context, id primitive.ObjectID) (*dto.FileData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFileByID", ctx, id)
	ret0, _ := ret[0].(*dto.FileData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFileByID indicates an expected call of FindFileByID.
func (mr *MockUserRepositoryMockRecorder) FindFileByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFileByID", reflect.TypeOf((*MockUserRepository)(nil).FindFileByID), ctx, id)
}

// FindUserByCpf mocks base method.
func (m *MockUserRepository) FindUserByCpf(cpf string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByCpf", cpf)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByCpf indicates an expected call of FindUserByCpf.
func (mr *MockUserRepositoryMockRecorder) FindUserByCpf(cpf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByCpf", reflect.TypeOf((*MockUserRepository)(nil).FindUserByCpf), cpf)
}

// FindUserByEmail mocks base method.
func (m *MockUserRepository) FindUserByEmail(email string) (dto.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", email)
	ret0, _ := ret[0].(dto.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockUserRepositoryMockRecorder) FindUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindUserByEmail), email)
}

// FindUserById mocks base method.
func (m *MockUserRepository) FindUserById(id string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserById", id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserById indicates an expected call of FindUserById.
func (mr *MockUserRepositoryMockRecorder) FindUserById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserById", reflect.TypeOf((*MockUserRepository)(nil).FindUserById), id)
}

// GetInactivePatientsCount mocks base method.
func (m *MockUserRepository) GetInactivePatientsCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInactivePatientsCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInactivePatientsCount indicates an expected call of GetInactivePatientsCount.
func (mr *MockUserRepositoryMockRecorder) GetInactivePatientsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInactivePatientsCount", reflect.TypeOf((*MockUserRepository)(nil).GetInactivePatientsCount))
}

// GetNewPatientsCountLast30Days mocks base method.
func (m *MockUserRepository) GetNewPatientsCountLast30Days() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewPatientsCountLast30Days")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewPatientsCountLast30Days indicates an expected call of GetNewPatientsCountLast30Days.
func (mr *MockUserRepositoryMockRecorder) GetNewPatientsCountLast30Days() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewPatientsCountLast30Days", reflect.TypeOf((*MockUserRepository)(nil).GetNewPatientsCountLast30Days))
}

// GetTopNeighborhoodsDemand mocks base method.
func (m *MockUserRepository) GetTopNeighborhoodsDemand(limit int) ([]dto0.NeighborhoodDemand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopNeighborhoodsDemand", limit)
	ret0, _ := ret[0].([]dto0.NeighborhoodDemand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopNeighborhoodsDemand indicates an expected call of GetTopNeighborhoodsDemand.
func (mr *MockUserRepositoryMockRecorder) GetTopNeighborhoodsDemand(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopNeighborhoodsDemand", reflect.TypeOf((*MockUserRepository)(nil).GetTopNeighborhoodsDemand), limit)
}

// GetTotalPatientsCount mocks base method.
func (m *MockUserRepository) GetTotalPatientsCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPatientsCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPatientsCount indicates an expected call of GetTotalPatientsCount.
func (mr *MockUserRepositoryMockRecorder) GetTotalPatientsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPatientsCount", reflect.TypeOf((*MockUserRepository)(nil).GetTotalPatientsCount))
}

// UpdatePasswordByUserID mocks base method.
func (m *MockUserRepository) UpdatePasswordByUserID(userID, hashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordByUserID", userID, hashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordByUserID indicates an expected call of UpdatePasswordByUserID.
func (mr *MockUserRepositoryMockRecorder) UpdatePasswordByUserID(userID, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordByUserID", reflect.TypeOf((*MockUserRepository)(nil).UpdatePasswordByUserID), userID, hashedPassword)
}

// UpdatePasswordLoggedByUserID mocks base method.
func (m *MockUserRepository) UpdatePasswordLoggedByUserID(userID, hashedPassword string, twoFactor bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordLoggedByUserID", userID, hashedPassword, twoFactor)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordLoggedByUserID indicates an expected call of UpdatePasswordLoggedByUserID.
func (mr *MockUserRepositoryMockRecorder) UpdatePasswordLoggedByUserID(userID, hashedPassword, twoFactor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordLoggedByUserID", reflect.TypeOf((*MockUserRepository)(nil).UpdatePasswordLoggedByUserID), userID, hashedPassword, twoFactor)
}

// UpdateTempCode mocks base method.
func (m *MockUserRepository) UpdateTempCode(userID string, code int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTempCode", userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTempCode indicates an expected call of UpdateTempCode.
func (mr *MockUserRepositoryMockRecorder) UpdateTempCode(userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTempCode", reflect.TypeOf((*MockUserRepository)(nil).UpdateTempCode), userID, code)
}

// UpdateUser mocks base method.
func (m *MockUserRepository) UpdateUser(userId string, userUpdated bson.M) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", userId, userUpdated)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepositoryMockRecorder) UpdateUser(userId, userUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), userId, userUpdated)
}

// UpdateUserFields mocks base method.
func (m *MockUserRepository) UpdateUserFields(userId string, updates map[string]any) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserFields", userId, updates)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserFields indicates an expected call of UpdateUserFields.
func (mr *MockUserRepositoryMockRecorder) UpdateUserFields(userId, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserFields", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserFields), userId, updates)
}

// UploadFile mocks base method.
func (m *MockUserRepository) UploadFile(file io.Reader, fileName, contentType string) (primitive.ObjectID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", file, fileName, contentType)
	ret0, _ := ret[0].(primitive.ObjectID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockUserRepositoryMockRecorder) UploadFile(file, fileName, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockUserRepository)(nil).UploadFile), file, fileName, contentType)
}

// UserExistsByEmail mocks base method.
func (m *MockUserRepository) UserExistsByEmail(email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserExistsByEmail", email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserExistsByEmail indicates an expected call of UserExistsByEmail.
func (mr *MockUserRepositoryMockRecorder) UserExistsByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserExistsByEmail", reflect.TypeOf((*MockUserRepository)(nil).UserExistsByEmail), email)
}
