// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/nurseRepository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/nurseRepository.go -destination=internal/repository/mocks/mock_nurseRepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	dto "medassist/internal/auth/dto"
	model "medassist/internal/model"
	dto0 "medassist/internal/nurse/dto"
	dto1 "medassist/internal/user/dto"
	reflect "reflect"

	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockNurseRepository is a mock of NurseRepository interface.
type MockNurseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNurseRepositoryMockRecorder
	isgomock struct{}
}

// MockNurseRepositoryMockRecorder is the mock recorder for MockNurseRepository.
type MockNurseRepositoryMockRecorder struct {
	mock *MockNurseRepository
}

// NewMockNurseRepository creates a new mock instance.
func NewMockNurseRepository(ctrl *gomock.Controller) *MockNurseRepository {
	mock := &MockNurseRepository{ctrl: ctrl}
	mock.recorder = &MockNurseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNurseRepository) EXPECT() *MockNurseRepositoryMockRecorder {
	return m.recorder
}

// CreateNurse mocks base method.
func (m *MockNurseRepository) CreateNurse(nurse *model.Nurse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNurse", nurse)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNurse indicates an expected call of CreateNurse.
func (mr *MockNurseRepositoryMockRecorder) CreateNurse(nurse any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNurse", reflect.TypeOf((*MockNurseRepository)(nil).CreateNurse), nurse)
}

// DeleteNurse mocks base method.
func (m *MockNurseRepository) DeleteNurse(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNurse", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNurse indicates an expected call of DeleteNurse.
func (mr *MockNurseRepositoryMockRecorder) DeleteNurse(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNurse", reflect.TypeOf((*MockNurseRepository)(nil).DeleteNurse), id)
}

// FindAllNurses mocks base method.
func (m *MockNurseRepository) FindAllNurses() ([]model.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllNurses")
	ret0, _ := ret[0].([]model.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllNurses indicates an expected call of FindAllNurses.
func (mr *MockNurseRepositoryMockRecorder) FindAllNurses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllNurses", reflect.TypeOf((*MockNurseRepository)(nil).FindAllNurses))
}

// FindAllNursesNotVerified mocks base method.
func (m *MockNurseRepository) FindAllNursesNotVerified() ([]model.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllNursesNotVerified")
	ret0, _ := ret[0].([]model.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllNursesNotVerified indicates an expected call of FindAllNursesNotVerified.
func (mr *MockNurseRepositoryMockRecorder) FindAllNursesNotVerified() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllNursesNotVerified", reflect.TypeOf((*MockNurseRepository)(nil).FindAllNursesNotVerified))
}

// FindAuthNurseByID mocks base method.
func (m *MockNurseRepository) FindAuthNurseByID(id string) (dto.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAuthNurseByID", id)
	ret0, _ := ret[0].(dto.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAuthNurseByID indicates an expected call of FindAuthNurseByID.
func (mr *MockNurseRepositoryMockRecorder) FindAuthNurseByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAuthNurseByID", reflect.TypeOf((*MockNurseRepository)(nil).FindAuthNurseByID), id)
}

// FindNurseByCoren mocks base method.
func (m *MockNurseRepository) FindNurseByCoren(coren string) (model.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNurseByCoren", coren)
	ret0, _ := ret[0].(model.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNurseByCoren indicates an expected call of FindNurseByCoren.
func (mr *MockNurseRepositoryMockRecorder) FindNurseByCoren(coren any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNurseByCoren", reflect.TypeOf((*MockNurseRepository)(nil).FindNurseByCoren), coren)
}

// FindNurseByCpf mocks base method.
func (m *MockNurseRepository) FindNurseByCpf(cpf string) (model.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNurseByCpf", cpf)
	ret0, _ := ret[0].(model.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNurseByCpf indicates an expected call of FindNurseByCpf.
func (mr *MockNurseRepositoryMockRecorder) FindNurseByCpf(cpf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNurseByCpf", reflect.TypeOf((*MockNurseRepository)(nil).FindNurseByCpf), cpf)
}

// FindNurseByEmail mocks base method.
func (m *MockNurseRepository) FindNurseByEmail(email string) (dto.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNurseByEmail", email)
	ret0, _ := ret[0].(dto.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNurseByEmail indicates an expected call of FindNurseByEmail.
func (mr *MockNurseRepositoryMockRecorder) FindNurseByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNurseByEmail", reflect.TypeOf((*MockNurseRepository)(nil).FindNurseByEmail), email)
}

// FindNurseById mocks base method.
func (m *MockNurseRepository) FindNurseById(id string) (model.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNurseById", id)
	ret0, _ := ret[0].(model.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNurseById indicates an expected call of FindNurseById.
func (mr *MockNurseRepositoryMockRecorder) FindNurseById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNurseById", reflect.TypeOf((*MockNurseRepository)(nil).FindNurseById), id)
}

// GetAllNurses mocks base method.
func (m *MockNurseRepository) GetAllNurses(patientCity string) ([]dto1.AllNursesListDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNurses", patientCity)
	ret0, _ := ret[0].([]dto1.AllNursesListDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNurses indicates an expected call of GetAllNurses.
func (mr *MockNurseRepositoryMockRecorder) GetAllNurses(patientCity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNurses", reflect.TypeOf((*MockNurseRepository)(nil).GetAllNurses), patientCity)
}

// GetAllOnlineNurses mocks base method.
func (m *MockNurseRepository) GetAllOnlineNurses(patientCity string, latitude, longitude float64) ([]dto1.AllNursesListDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOnlineNurses", patientCity, latitude, longitude)
	ret0, _ := ret[0].([]dto1.AllNursesListDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOnlineNurses indicates an expected call of GetAllOnlineNurses.
func (mr *MockNurseRepositoryMockRecorder) GetAllOnlineNurses(patientCity, latitude, longitude any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOnlineNurses", reflect.TypeOf((*MockNurseRepository)(nil).GetAllOnlineNurses), patientCity, latitude, longitude)
}

// GetAverageNurseRating mocks base method.
func (m *MockNurseRepository) GetAverageNurseRating() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageNurseRating")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageNurseRating indicates an expected call of GetAverageNurseRating.
func (mr *MockNurseRepositoryMockRecorder) GetAverageNurseRating() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageNurseRating", reflect.TypeOf((*MockNurseRepository)(nil).GetAverageNurseRating))
}

// GetIdsNursesPendents mocks base method.
func (m *MockNurseRepository) GetIdsNursesPendents() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdsNursesPendents")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdsNursesPendents indicates an expected call of GetIdsNursesPendents.
func (mr *MockNurseRepositoryMockRecorder) GetIdsNursesPendents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdsNursesPendents", reflect.TypeOf((*MockNurseRepository)(nil).GetIdsNursesPendents))
}

// GetInactiveNursesCount mocks base method.
func (m *MockNurseRepository) GetInactiveNursesCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInactiveNursesCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInactiveNursesCount indicates an expected call of GetInactiveNursesCount.
func (mr *MockNurseRepositoryMockRecorder) GetInactiveNursesCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInactiveNursesCount", reflect.TypeOf((*MockNurseRepository)(nil).GetInactiveNursesCount))
}

// GetMostCommonSpecialization mocks base method.
func (m *MockNurseRepository) GetMostCommonSpecialization() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMostCommonSpecialization")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMostCommonSpecialization indicates an expected call of GetMostCommonSpecialization.
func (mr *MockNurseRepositoryMockRecorder) GetMostCommonSpecialization() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostCommonSpecialization", reflect.TypeOf((*MockNurseRepository)(nil).GetMostCommonSpecialization))
}

// GetNewNursesCountLast30Days mocks base method.
func (m *MockNurseRepository) GetNewNursesCountLast30Days() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewNursesCountLast30Days")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewNursesCountLast30Days indicates an expected call of GetNewNursesCountLast30Days.
func (mr *MockNurseRepositoryMockRecorder) GetNewNursesCountLast30Days() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewNursesCountLast30Days", reflect.TypeOf((*MockNurseRepository)(nil).GetNewNursesCountLast30Days))
}

// GetOnlineNursesCount mocks base method.
func (m *MockNurseRepository) GetOnlineNursesCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnlineNursesCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnlineNursesCount indicates an expected call of GetOnlineNursesCount.
func (mr *MockNurseRepositoryMockRecorder) GetOnlineNursesCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnlineNursesCount", reflect.TypeOf((*MockNurseRepository)(nil).GetOnlineNursesCount))
}

// GetPendingApprovalNursesInfo mocks base method.
func (m *MockNurseRepository) GetPendingApprovalNursesInfo() ([]dto0.PendingNurseInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingApprovalNursesInfo")
	ret0, _ := ret[0].([]dto0.PendingNurseInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingApprovalNursesInfo indicates an expected call of GetPendingApprovalNursesInfo.
func (mr *MockNurseRepositoryMockRecorder) GetPendingApprovalNursesInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingApprovalNursesInfo", reflect.TypeOf((*MockNurseRepository)(nil).GetPendingApprovalNursesInfo))
}

// GetPendingApprovalsCount mocks base method.
func (m *MockNurseRepository) GetPendingApprovalsCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingApprovalsCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingApprovalsCount indicates an expected call of GetPendingApprovalsCount.
func (mr *MockNurseRepositoryMockRecorder) GetPendingApprovalsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingApprovalsCount", reflect.TypeOf((*MockNurseRepository)(nil).GetPendingApprovalsCount))
}

// GetTotalNursesCount mocks base method.
func (m *MockNurseRepository) GetTotalNursesCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalNursesCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalNursesCount indicates an expected call of GetTotalNursesCount.
func (mr *MockNurseRepositoryMockRecorder) GetTotalNursesCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalNursesCount", reflect.TypeOf((*MockNurseRepository)(nil).GetTotalNursesCount))
}

// SetLicenseDocumentID mocks base method.
func (m *MockNurseRepository) SetLicenseDocumentID(nurseID, documentID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLicenseDocumentID", nurseID, documentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLicenseDocumentID indicates an expected call of SetLicenseDocumentID.
func (mr *MockNurseRepositoryMockRecorder) SetLicenseDocumentID(nurseID, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLicenseDocumentID", reflect.TypeOf((*MockNurseRepository)(nil).SetLicenseDocumentID), nurseID, documentID)
}

// UpdateNurse mocks base method.
func (m *MockNurseRepository) UpdateNurse(nurseId string, userUpdated bson.M) (model.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNurse", nurseId, userUpdated)
	ret0, _ := ret[0].(model.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNurse indicates an expected call of UpdateNurse.
func (mr *MockNurseRepositoryMockRecorder) UpdateNurse(nurseId, userUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNurse", reflect.TypeOf((*MockNurseRepository)(nil).UpdateNurse), nurseId, userUpdated)
}

// UpdateNurseFields mocks base method.
func (m *MockNurseRepository) UpdateNurseFields(id string, updates map[string]any) (model.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNurseFields", id, updates)
	ret0, _ := ret[0].(model.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNurseFields indicates an expected call of UpdateNurseFields.
func (mr *MockNurseRepositoryMockRecorder) UpdateNurseFields(id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNurseFields", reflect.TypeOf((*MockNurseRepository)(nil).UpdateNurseFields), id, updates)
}

// UpdatePasswordByNurseID mocks base method.
func (m *MockNurseRepository) UpdatePasswordByNurseID(userID, hashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordByNurseID", userID, hashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordByNurseID indicates an expected call of UpdatePasswordByNurseID.
func (mr *MockNurseRepositoryMockRecorder) UpdatePasswordByNurseID(userID, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordByNurseID", reflect.TypeOf((*MockNurseRepository)(nil).UpdatePasswordByNurseID), userID, hashedPassword)
}

// UpdatePasswordLoggedByNurseID mocks base method.
func (m *MockNurseRepository) UpdatePasswordLoggedByNurseID(userID, hashedPassword string, twoFactor bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordLoggedByNurseID", userID, hashedPassword, twoFactor)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordLoggedByNurseID indicates an expected call of UpdatePasswordLoggedByNurseID.
func (mr *MockNurseRepositoryMockRecorder) UpdatePasswordLoggedByNurseID(userID, hashedPassword, twoFactor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordLoggedByNurseID", reflect.TypeOf((*MockNurseRepository)(nil).UpdatePasswordLoggedByNurseID), userID, hashedPassword, twoFactor)
}

// UpdateStripeAccountId mocks base method.
func (m *MockNurseRepository) UpdateStripeAccountId(nurseId, stripeAccountId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStripeAccountId", nurseId, stripeAccountId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStripeAccountId indicates an expected call of UpdateStripeAccountId.
func (mr *MockNurseRepositoryMockRecorder) UpdateStripeAccountId(nurseId, stripeAccountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStripeAccountId", reflect.TypeOf((*MockNurseRepository)(nil).UpdateStripeAccountId), nurseId, stripeAccountId)
}

// UpdateTempCode mocks base method.
func (m *MockNurseRepository) UpdateTempCode(userID string, code int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTempCode", userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTempCode indicates an expected call of UpdateTempCode.
func (mr *MockNurseRepositoryMockRecorder) UpdateTempCode(userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTempCode", reflect.TypeOf((*MockNurseRepository)(nil).UpdateTempCode), userID, code)
}

// UploadFile mocks base method.
func (m *MockNurseRepository) UploadFile(file io.Reader, fileName, contentType string) (primitive.ObjectID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", file, fileName, contentType)
	ret0, _ := ret[0].(primitive.ObjectID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockNurseRepositoryMockRecorder) UploadFile(file, fileName, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockNurseRepository)(nil).UploadFile), file, fileName, contentType)
}
