// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/visitRepository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/visitRepository.go -destination=internal/repository/mocks/mock_visitRepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "medassist/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVisitRepository is a mock of VisitRepository interface.
type MockVisitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVisitRepositoryMockRecorder
	isgomock struct{}
}

// MockVisitRepositoryMockRecorder is the mock recorder for MockVisitRepository.
type MockVisitRepositoryMockRecorder struct {
	mock *MockVisitRepository
}

// NewMockVisitRepository creates a new mock instance.
func NewMockVisitRepository(ctrl *gomock.Controller) *MockVisitRepository {
	mock := &MockVisitRepository{ctrl: ctrl}
	mock.recorder = &MockVisitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVisitRepository) EXPECT() *MockVisitRepositoryMockRecorder {
	return m.recorder
}

// CreateVisit mocks base method.
func (m *MockVisitRepository) CreateVisit(visit model.Visit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVisit", visit)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVisit indicates an expected call of CreateVisit.
func (mr *MockVisitRepositoryMockRecorder) CreateVisit(visit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVisit", reflect.TypeOf((*MockVisitRepository)(nil).CreateVisit), visit)
}

// DeleteVisit mocks base method.
func (m *MockVisitRepository) DeleteVisit(visitId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVisit", visitId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVisit indicates an expected call of DeleteVisit.
func (mr *MockVisitRepositoryMockRecorder) DeleteVisit(visitId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVisit", reflect.TypeOf((*MockVisitRepository)(nil).DeleteVisit), visitId)
}

// FindAllCompletedVisitsForPatient mocks base method.
func (m *MockVisitRepository) FindAllCompletedVisitsForPatient(patientId string) ([]model.Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllCompletedVisitsForPatient", patientId)
	ret0, _ := ret[0].([]model.Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllCompletedVisitsForPatient indicates an expected call of FindAllCompletedVisitsForPatient.
func (mr *MockVisitRepositoryMockRecorder) FindAllCompletedVisitsForPatient(patientId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllCompletedVisitsForPatient", reflect.TypeOf((*MockVisitRepository)(nil).FindAllCompletedVisitsForPatient), patientId)
}

// FindAllPendingVisitsForNurse mocks base method.
func (m *MockVisitRepository) FindAllPendingVisitsForNurse(nurseId string) ([]model.Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllPendingVisitsForNurse", nurseId)
	ret0, _ := ret[0].([]model.Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllPendingVisitsForNurse indicates an expected call of FindAllPendingVisitsForNurse.
func (mr *MockVisitRepositoryMockRecorder) FindAllPendingVisitsForNurse(nurseId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllPendingVisitsForNurse", reflect.TypeOf((*MockVisitRepository)(nil).FindAllPendingVisitsForNurse), nurseId)
}

// FindAllVisits mocks base method.
func (m *MockVisitRepository) FindAllVisits() ([]model.Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllVisits")
	ret0, _ := ret[0].([]model.Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllVisits indicates an expected call of FindAllVisits.
func (mr *MockVisitRepositoryMockRecorder) FindAllVisits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllVisits", reflect.TypeOf((*MockVisitRepository)(nil).FindAllVisits))
}

// FindAllVisitsForNurse mocks base method.
func (m *MockVisitRepository) FindAllVisitsForNurse(nurseId string) ([]model.Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllVisitsForNurse", nurseId)
	ret0, _ := ret[0].([]model.Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllVisitsForNurse indicates an expected call of FindAllVisitsForNurse.
func (mr *MockVisitRepositoryMockRecorder) FindAllVisitsForNurse(nurseId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllVisitsForNurse", reflect.TypeOf((*MockVisitRepository)(nil).FindAllVisitsForNurse), nurseId)
}

// FindAllVisitsForPatient mocks base method.
func (m *MockVisitRepository) FindAllVisitsForPatient(patientId string) ([]model.Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllVisitsForPatient", patientId)
	ret0, _ := ret[0].([]model.Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllVisitsForPatient indicates an expected call of FindAllVisitsForPatient.
func (mr *MockVisitRepositoryMockRecorder) FindAllVisitsForPatient(patientId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllVisitsForPatient", reflect.TypeOf((*MockVisitRepository)(nil).FindAllVisitsForPatient), patientId)
}

// FindVisitById mocks base method.
func (m *MockVisitRepository) FindVisitById(id string) (model.Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVisitById", id)
	ret0, _ := ret[0].(model.Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVisitById indicates an expected call of FindVisitById.
func (mr *MockVisitRepositoryMockRecorder) FindVisitById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVisitById", reflect.TypeOf((*MockVisitRepository)(nil).FindVisitById), id)
}

// GetCompletedVisitsCountLast30Days mocks base method.
func (m *MockVisitRepository) GetCompletedVisitsCountLast30Days() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletedVisitsCountLast30Days")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedVisitsCountLast30Days indicates an expected call of GetCompletedVisitsCountLast30Days.
func (mr *MockVisitRepositoryMockRecorder) GetCompletedVisitsCountLast30Days() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedVisitsCountLast30Days", reflect.TypeOf((*MockVisitRepository)(nil).GetCompletedVisitsCountLast30Days))
}

// GetTotalRevenueLast30Days mocks base method.
func (m *MockVisitRepository) GetTotalRevenueLast30Days() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalRevenueLast30Days")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalRevenueLast30Days indicates an expected call of GetTotalRevenueLast30Days.
func (mr *MockVisitRepositoryMockRecorder) GetTotalRevenueLast30Days() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalRevenueLast30Days", reflect.TypeOf((*MockVisitRepository)(nil).GetTotalRevenueLast30Days))
}

// GetTotalVisitsCount mocks base method.
func (m *MockVisitRepository) GetTotalVisitsCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalVisitsCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalVisitsCount indicates an expected call of GetTotalVisitsCount.
func (mr *MockVisitRepositoryMockRecorder) GetTotalVisitsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalVisitsCount", reflect.TypeOf((*MockVisitRepository)(nil).GetTotalVisitsCount))
}

// GetVisitsTodayCount mocks base method.
func (m *MockVisitRepository) GetVisitsTodayCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVisitsTodayCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVisitsTodayCount indicates an expected call of GetVisitsTodayCount.
func (mr *MockVisitRepositoryMockRecorder) GetVisitsTodayCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVisitsTodayCount", reflect.TypeOf((*MockVisitRepository)(nil).GetVisitsTodayCount))
}

// UpdateVisitFields mocks base method.
func (m *MockVisitRepository) UpdateVisitFields(id string, updates map[string]any) (model.Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVisitFields", id, updates)
	ret0, _ := ret[0].(model.Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVisitFields indicates an expected call of UpdateVisitFields.
func (mr *MockVisitRepositoryMockRecorder) UpdateVisitFields(id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVisitFields", reflect.TypeOf((*MockVisitRepository)(nil).UpdateVisitFields), id, updates)
}
