// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/userService.go
//
// Generated by this command:
//
//	mockgen -source=internal/user/userService.go -destination=internal/user/mocks/mock_userService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "medassist/internal/admin/dto"
	dto0 "medassist/internal/auth/dto"
	dto1 "medassist/internal/user/dto"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// AddReview mocks base method.
func (m *MockUserService) AddReview(userId, visitId string, reviewDto dto1.ReviewDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReview", userId, visitId, reviewDto)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReview indicates an expected call of AddReview.
func (mr *MockUserServiceMockRecorder) AddReview(userId, visitId, reviewDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReview", reflect.TypeOf((*MockUserService)(nil).AddReview), userId, visitId, reviewDto)
}

// ConfirmVisitService mocks base method.
func (m *MockUserService) ConfirmVisitService(visitId, patientId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmVisitService", visitId, patientId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmVisitService indicates an expected call of ConfirmVisitService.
func (mr *MockUserServiceMockRecorder) ConfirmVisitService(visitId, patientId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmVisitService", reflect.TypeOf((*MockUserService)(nil).ConfirmVisitService), visitId, patientId)
}

// ContactUsMessage mocks base method.
func (m *MockUserService) ContactUsMessage(contactUsDto dto1.ContactUsDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContactUsMessage", contactUsDto)
	ret0, _ := ret[0].(error)
	return ret0
}

// ContactUsMessage indicates an expected call of ContactUsMessage.
func (mr *MockUserServiceMockRecorder) ContactUsMessage(contactUsDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContactUsMessage", reflect.TypeOf((*MockUserService)(nil).ContactUsMessage), contactUsDto)
}

// DeleteUser mocks base method.
func (m *MockUserService) DeleteUser(patientId string, deleteAccountPasswordDto dto1.DeleteAccountPasswordDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", patientId, deleteAccountPasswordDto)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMockRecorder) DeleteUser(patientId, deleteAccountPasswordDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserService)(nil).DeleteUser), patientId, deleteAccountPasswordDto)
}

// FindAllVisits mocks base method.
func (m *MockUserService) FindAllVisits(patientId string) (dto1.VisitsResponseDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllVisits", patientId)
	ret0, _ := ret[0].(dto1.VisitsResponseDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllVisits indicates an expected call of FindAllVisits.
func (mr *MockUserServiceMockRecorder) FindAllVisits(patientId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllVisits", reflect.TypeOf((*MockUserService)(nil).FindAllVisits), patientId)
}

// GetAllNurses mocks base method.
func (m *MockUserService) GetAllNurses(patientId string) ([]dto1.AllNursesListDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNurses", patientId)
	ret0, _ := ret[0].([]dto1.AllNursesListDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNurses indicates an expected call of GetAllNurses.
func (mr *MockUserServiceMockRecorder) GetAllNurses(patientId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNurses", reflect.TypeOf((*MockUserService)(nil).GetAllNurses), patientId)
}

// GetFileByID mocks base method.
func (m *MockUserService) GetFileByID(ctx context.Context, id primitive.ObjectID) (*dto0.FileData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByID", ctx, id)
	ret0, _ := ret[0].(*dto0.FileData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByID indicates an expected call of GetFileByID.
func (mr *MockUserServiceMockRecorder) GetFileByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByID", reflect.TypeOf((*MockUserService)(nil).GetFileByID), ctx, id)
}

// GetNurseProfile mocks base method.
func (m *MockUserService) GetNurseProfile(nurseId string) (dto1.NurseProfileResponseDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNurseProfile", nurseId)
	ret0, _ := ret[0].(dto1.NurseProfileResponseDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNurseProfile indicates an expected call of GetNurseProfile.
func (mr *MockUserServiceMockRecorder) GetNurseProfile(nurseId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNurseProfile", reflect.TypeOf((*MockUserService)(nil).GetNurseProfile), nurseId)
}

// GetOnlineNurses mocks base method.
func (m *MockUserService) GetOnlineNurses(userId string) ([]dto1.AllNursesListDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnlineNurses", userId)
	ret0, _ := ret[0].([]dto1.AllNursesListDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnlineNurses indicates an expected call of GetOnlineNurses.
func (mr *MockUserServiceMockRecorder) GetOnlineNurses(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnlineNurses", reflect.TypeOf((*MockUserService)(nil).GetOnlineNurses), userId)
}

// GetPatientProfile mocks base method.
func (m *MockUserService) GetPatientProfile(patientId string) (dto1.PatientProfileResponseDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatientProfile", patientId)
	ret0, _ := ret[0].(dto1.PatientProfileResponseDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatientProfile indicates an expected call of GetPatientProfile.
func (mr *MockUserServiceMockRecorder) GetPatientProfile(patientId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatientProfile", reflect.TypeOf((*MockUserService)(nil).GetPatientProfile), patientId)
}

// GetPatientVisitInfo mocks base method.
func (m *MockUserService) GetPatientVisitInfo(patientId, visitId string) (dto1.PatientVisitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatientVisitInfo", patientId, visitId)
	ret0, _ := ret[0].(dto1.PatientVisitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatientVisitInfo indicates an expected call of GetPatientVisitInfo.
func (mr *MockUserServiceMockRecorder) GetPatientVisitInfo(patientId, visitId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatientVisitInfo", reflect.TypeOf((*MockUserService)(nil).GetPatientVisitInfo), patientId, visitId)
}

// ImmediateVisitSolicitation mocks base method.
func (m *MockUserService) ImmediateVisitSolicitation(patientId string, immediateVisitDto dto1.ImmediateVisitDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImmediateVisitSolicitation", patientId, immediateVisitDto)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImmediateVisitSolicitation indicates an expected call of ImmediateVisitSolicitation.
func (mr *MockUserServiceMockRecorder) ImmediateVisitSolicitation(patientId, immediateVisitDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImmediateVisitSolicitation", reflect.TypeOf((*MockUserService)(nil).ImmediateVisitSolicitation), patientId, immediateVisitDto)
}

// UpdateUser mocks base method.
func (m *MockUserService) UpdateUser(userId string, updates map[string]any) (dto.UserTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", userId, updates)
	ret0, _ := ret[0].(dto.UserTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceMockRecorder) UpdateUser(userId, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserService)(nil).UpdateUser), userId, updates)
}

// VisitSolicitation mocks base method.
func (m *MockUserService) VisitSolicitation(userId string, createVisitDto dto1.CreateVisitDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VisitSolicitation", userId, createVisitDto)
	ret0, _ := ret[0].(error)
	return ret0
}

// VisitSolicitation indicates an expected call of VisitSolicitation.
func (mr *MockUserServiceMockRecorder) VisitSolicitation(userId, createVisitDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitSolicitation", reflect.TypeOf((*MockUserService)(nil).VisitSolicitation), userId, createVisitDto)
}
