// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/approve/{id}": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Altera o status do enfermeiro para 'verificado' (verification_seal: true). Requer autenticação de Admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Aprova o cadastro de um enfermeiro",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Enfermeiro a ser aprovado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Enfermeiro aprovado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseString"
                        }
                    },
                    "400": {
                        "description": "ID inválido ou erro na aprovação",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Administrador)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/dashboard": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna as principais métricas e KPIs para a tela de dashboard do administrador. Requer autenticação de Admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Dados do Dashboard Administrativo",
                "responses": {
                    "200": {
                        "description": "Dados de dashboard carregados com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessDashboardResponse"
                        }
                    },
                    "400": {
                        "description": "Erro ao carregar dados",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Administrador)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/documents/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna uma lista de documentos (com URLs de download) de um enfermeiro específico para aprovação. Requer autenticação de Admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Obtém documentos do enfermeiro para análise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Enfermeiro (Nurse ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Documentos retornados com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessDocumentsResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido ou erro ao buscar documentos",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Administrador)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/download/{id}": {
            "get": {
                "description": "Faz o download de um arquivo (como um documento de enfermeiro) com base no seu ObjectID do GridFS.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Baixa um arquivo do GridFS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Arquivo (File ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "O arquivo para download",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "ID inválido ou Arquivo não encontrado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao enviar o arquivo",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/reject/{id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Envia um email ao enfermeiro com o motivo da rejeição. Requer autenticação de Admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Rejeita o cadastro de um enfermeiro",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Enfermeiro a ser rejeitado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Objeto contendo a descrição/motivo da rejeição",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RejectDescription"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Enfermeiro rejeitado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseString"
                        }
                    },
                    "400": {
                        "description": "ID inválido, corpo da requisição inválido ou erro na rejeição",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Administrador)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/user/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Permite ao administrador deletar um usuário (Paciente ou Enfermeiro) permanentemente. Requer autenticação de Admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Deleta um usuário (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Usuário a ser deletado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuário deletado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseNoData"
                        }
                    },
                    "400": {
                        "description": "ID inválido ou erro ao deletar",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Administrador)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Permite ao administrador atualizar campos de um usuário (Paciente ou Enfermeiro). Requer autenticação de Admin.\nCampos protegidos (id, created_at, updated_at) não podem ser atualizados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Atualiza um usuário (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Usuário a ser atualizado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos para atualizar (JSON arbitrário). Ex: {\\",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuário atualizado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessUserTypeResponse"
                        }
                    },
                    "400": {
                        "description": "JSON inválido, ID não encontrado ou campo protegido",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Administrador)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna listas completas de usuários, enfermeiros e visitas para gerenciamento do admin. Requer autenticação de Admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Listas de gerenciamento (Usuários, Enfermeiros, Visitas)",
                "responses": {
                    "200": {
                        "description": "Listas retornadas com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessUserListsResponse"
                        }
                    },
                    "400": {
                        "description": "Erro ao buscar listas",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Administrador)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/visit/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Permite ao administrador deletar uma visita permanentemente. Requer autenticação de Admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Deleta uma visita (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da Visita a ser deletada",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Visita deletada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseNoData"
                        }
                    },
                    "400": {
                        "description": "ID inválido ou erro ao deletar",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Administrador)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Permite ao administrador atualizar campos de uma visita. Requer autenticação de Admin.\nCampos protegidos (id, created_at, updated_at) não podem ser atualizados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Atualiza uma visita (Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da Visita a ser atualizada",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos para atualizar (JSON arbitrário). Ex: {\\",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Visita atualizada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessVisitTypeResponse"
                        }
                    },
                    "400": {
                        "description": "JSON inválido, ID não encontrado ou campo protegido",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Administrador)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/adm": {
            "post": {
                "description": "Endpoint para configuração inicial. Cria o primeiro usuário administrador no banco de dados se ele ainda não existir.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Cria o primeiro usuário Administrador",
                "responses": {
                    "200": {
                        "description": "Resposta de sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseNoData"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/code": {
            "patch": {
                "description": "Usado para autenticação de dois fatores ou verificação de email. Envia um código temporário.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Envia código de autenticação por email",
                "parameters": [
                    {
                        "description": "Email para o qual enviar o código",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EmailAuthRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Código enviado com sucesso (retorna o código ou status)",
                        "schema": {
                            "$ref": "#/definitions/dto.CodeResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/email": {
            "post": {
                "description": "Inicia o fluxo de \"esqueci minha senha\" enviando um email com código/token para o usuário.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Envia email de recuperação de senha",
                "parameters": [
                    {
                        "description": "Email do usuário que esqueceu a senha",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ForgotPasswordRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email enviado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseNoData"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida (e.g., email mal formatado ou não encontrado)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logged/password": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Permite que um usuário (paciente ou enfermeiro) logado altere sua própria senha. Requer autenticação JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Altera a senha do usuário logado",
                "parameters": [
                    {
                        "description": "Dados da nova senha",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangePasswordBothRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Senha ou configurações atualizadas com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseNoData"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Não autorizado (Token JWT inválido ou ausente)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Proibido (Usuário não é Paciente ou Enfermeiro)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Autentica um usuário (paciente ou enfermeiro) e retorna um token JWT e dados do usuário.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login de Usuário",
                "parameters": [
                    {
                        "description": "Credenciais de Login (email e senha)",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login bem-sucedido",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessValidateCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida ou credenciais incorretas",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/nurse": {
            "post": {
                "description": "Cria uma nova solicitação de cadastro de enfermeiro, com dados e upload de documentos obrigatórios.",
                "consumes": [
                    "multipart/form-data",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Auth",
                    "Auth"
                ],
                "summary": "Registro de Novo Enfermeiro (Nurse)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome completo",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email válido",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Telefone (com DDD)",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CEP",
                        "name": "cep",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rua",
                        "name": "street",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Número",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Complemento (Opcional)",
                        "name": "complement",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bairro",
                        "name": "neighborhood",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cidade",
                        "name": "city",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UF",
                        "name": "uf",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CPF",
                        "name": "cpf",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chave PIX",
                        "name": "pix_key",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Senha",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Registro Coren",
                        "name": "coren",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Especialização (ex: Pediatria)",
                        "name": "specialization",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Departamento (ex: Enfermagem)",
                        "name": "department",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Anos de Experiência (número)",
                        "name": "years_experience",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Biografia / Descrição breve",
                        "name": "bio",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Horário de início (ex: 08:00)",
                        "name": "start_time",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Horário de término (ex: 18:00)",
                        "name": "end_time",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Documento de Licença (CNH/RG)",
                        "name": "license_document",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Comprovante de Qualificações/Diplomas",
                        "name": "qualifications",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Registro Geral (RG)",
                        "name": "general_register",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Comprovante de Residência",
                        "name": "residence_comprovant",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Imagem de Perfil",
                        "name": "profile_image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cadastro solicitado com sucesso (retorna o objeto Nurse)",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseNurse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos, arquivos faltando ou formato incorreto",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "description": "Altera a senha do usuário usando um token de reset (obtido no fluxo \"esqueci minha senha\").",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Reseta a senha do usuário",
                "parameters": [
                    {
                        "description": "Token de reset e nova senha",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Senha alterada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseNoData"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos (e.g., senha fraca)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token inválido ou expirado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/user": {
            "post": {
                "description": "Cria um novo usuário (paciente) no sistema, permitindo o upload de uma imagem de perfil.",
                "consumes": [
                    "multipart/form-data",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Auth",
                    "Auth"
                ],
                "summary": "Registro de Novo Usuário (Paciente)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome completo do usuário",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email válido do usuário",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Telefone do usuário (com DDD)",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bairro",
                        "name": "neighborhood",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cidade",
                        "name": "city",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Estado (UF)",
                        "name": "uf",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Complemento do endereço (Opcional)",
                        "name": "complement",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Número do endereço",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rua/Avenida",
                        "name": "street",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CEP",
                        "name": "cep",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CPF do usuário",
                        "name": "cpf",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Senha (deve seguir as regras de complexidade)",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Imagem de perfil (Opcional)",
                        "name": "image_profile",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuário criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos (validação falhou, e-mail/CPF duplicado, erro no arquivo)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/validate": {
            "post": {
                "description": "Valida o código temporário (enviado por email) e retorna um token de sessão e dados do usuário.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Valida código de autenticação",
                "parameters": [
                    {
                        "description": "Email e código para validação",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InputCodeDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Código validado com sucesso (retorna token e usuário)",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessValidateCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Código inválido (ou outros erros de requisição)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/validate-token": {
            "post": {
                "description": "Verifica se um token (enviado por email) é válido e não expirou, antes de permitir a troca da senha.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Valida um token de reset de senha",
                "parameters": [
                    {
                        "description": "Token de reset a ser validado",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ValidateTokenDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token válido",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessResponseNoData"
                        }
                    },
                    "400": {
                        "description": "Token é obrigatório",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token inválido ou expirado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/messages/{nurseId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna todas as mensagens entre o usuário logado (seja Paciente ou Enfermeiro) e um enfermeiro específico.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Histórico de mensagens com um enfermeiro",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Enfermeiro (com quem a conversa acontece)",
                        "name": "nurseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Histórico de mensagens retornado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessMessagesResponse"
                        }
                    },
                    "400": {
                        "description": "ID do enfermeiro inválido",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Usuário não autenticado",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar mensagens",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/nurse/conversations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna a lista de todas as conversas ativas do enfermeiro logado. Requer autenticação de Enfermeiro.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Lista de conversas do Enfermeiro",
                "responses": {
                    "200": {
                        "description": "Lista de conversas retornada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessConversationsResponse"
                        }
                    },
                    "401": {
                        "description": "Não autenticado ou ID de usuário inválido",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar conversas",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/patient/conversations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna a lista de todas as conversas ativas do paciente logado. Requer autenticação de Paciente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Lista de conversas do Paciente",
                "responses": {
                    "200": {
                        "description": "Lista de conversas retornada com sucesso",
                        "schema": {
                            "$ref": "#/definitions/utils.SuccessConversationsResponse"
                        }
                    },
                    "401": {
                        "description": "Não autenticado ou ID de usuário inválido",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar conversas",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ChangePasswordBothRequestDTO": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "two_fa": {
                    "type": "boolean"
                }
            }
        },
        "dto.CodeResponseDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        },
        "dto.ConversationDTO": {
            "type": "object",
            "properties": {
                "last_message": {
                    "type": "string"
                },
                "last_message_timestamp": {
                    "type": "string"
                },
                "partner_id": {
                    "type": "string"
                },
                "partner_image_id": {
                    "type": "string"
                },
                "partner_name": {
                    "type": "string"
                }
            }
        },
        "dto.DashboardAdminDataResponse": {
            "type": "object",
            "properties": {
                "average_nurse_rating": {
                    "type": "number"
                },
                "completed_visits_last_30_days": {
                    "type": "integer"
                },
                "most_common_specialization": {
                    "description": "Métricas Estratégicas",
                    "type": "string"
                },
                "new_nurses_last_30_days": {
                    "type": "integer"
                },
                "new_patients_last_30_days": {
                    "type": "integer"
                },
                "number_visits": {
                    "description": "Mudei para int64 para consistência",
                    "type": "integer"
                },
                "nurses_ids_pendent_approvations": {
                    "description": "Renomeei aqui",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.NursesFieldsForDashboardResponse"
                    }
                },
                "nurses_inactive": {
                    "type": "integer"
                },
                "nurses_online": {
                    "description": "Métricas de Atividade e Crescimento",
                    "type": "integer"
                },
                "patients_inactive": {
                    "type": "integer"
                },
                "pendent_approvations": {
                    "description": "Métricas de Gestão e Alertas",
                    "type": "integer"
                },
                "total_nurses": {
                    "description": "Métricas Principais (KPIs)",
                    "type": "integer"
                },
                "total_patients": {
                    "type": "integer"
                },
                "total_revenue_last_30_days": {
                    "type": "number"
                },
                "visits_today": {
                    "description": "Mudei para int64 para consistência",
                    "type": "integer"
                }
            }
        },
        "dto.DocumentInfoResponse": {
            "type": "object",
            "properties": {
                "download_url": {
                    "description": "A URL para baixar o arquivo",
                    "type": "string"
                },
                "image_id": {
                    "type": "string"
                },
                "name": {
                    "description": "Um nome amigável, ex: \"Documento de Licença (COREN)\"",
                    "type": "string"
                },
                "type": {
                    "description": "Um identificador, ex: \"license_document\"",
                    "type": "string"
                }
            }
        },
        "dto.EmailAuthRequestDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.ForgotPasswordRequestDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.InputCodeDto": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.LoginRequestDTO": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.NurseTypeResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "coren": {
                    "description": "registro profissional",
                    "type": "string"
                },
                "cpf": {
                    "type": "string"
                },
                "department": {
                    "description": "setor/hospital onde trabalha",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "first_access": {
                    "type": "boolean"
                },
                "hidden": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "pix_key": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "role": {
                    "type": "string"
                },
                "shift": {
                    "description": "manhã, tarde, noite",
                    "type": "string"
                },
                "specialization": {
                    "description": "área (ex: pediatrics, geriatrics, ER)",
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "verification_seal": {
                    "type": "boolean"
                },
                "years_experience": {
                    "type": "integer"
                }
            }
        },
        "dto.NursesFieldsForDashboardResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.RejectDescription": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                }
            }
        },
        "dto.ResetPasswordDTO": {
            "type": "object",
            "required": [
                "newPassword",
                "token"
            ],
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.UserListsResponse": {
            "type": "object",
            "properties": {
                "nurses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.NurseTypeResponse"
                    }
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UserTypeResponse"
                    }
                },
                "visits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.VisitTypeResponse"
                    }
                }
            }
        },
        "dto.UserTypeResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "cpf": {
                    "description": "PixKey      string ` + "`" + `json:\"pix_key\"` + "`" + `",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_access": {
                    "type": "boolean"
                },
                "hidden": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "dto.ValidateTokenDTO": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.VisitTypeResponse": {
            "type": "object",
            "properties": {
                "cancel_reason": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nurse_id": {
                    "type": "string"
                },
                "nurse_name": {
                    "type": "string"
                },
                "patient_email": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                },
                "patient_name": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                },
                "visit_date": {
                    "type": "string"
                },
                "visit_type": {
                    "type": "string"
                }
            }
        },
        "model.Message": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "receiver_id": {
                    "type": "string"
                },
                "sender_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "model.Nurse": {
            "type": "object",
            "required": [
                "address",
                "city",
                "coren",
                "cpf",
                "email",
                "end_time",
                "general_register_id",
                "license_document_id",
                "name",
                "neighborhood",
                "number",
                "online",
                "password",
                "phone",
                "pix_key",
                "profile_image_id",
                "qualifications_id",
                "residence_comprovant_id",
                "role",
                "start_time",
                "street",
                "uf",
                "verification_seal"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "available_neighborhoods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "bio": {
                    "type": "string"
                },
                "cep": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "complement": {
                    "type": "string"
                },
                "coren": {
                    "description": "registro profissional",
                    "type": "string"
                },
                "cpf": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "days_available": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "department": {
                    "description": "setor/hospital onde trabalha",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "first_access": {
                    "type": "boolean"
                },
                "general_register_id": {
                    "type": "string"
                },
                "hidden": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "license_document_id": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "max_patients_per_day": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "neighborhood": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "pix_key": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "profile_image_id": {
                    "type": "string"
                },
                "qualifications": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "qualifications_id": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "residence_comprovant_id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "shift": {
                    "description": "manhã, tarde, noite",
                    "type": "string"
                },
                "specialization": {
                    "description": "área (ex: pediatrics, geriatrics, ER)",
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "stripe_account_id": {
                    "type": "string"
                },
                "temp_code": {
                    "type": "integer"
                },
                "two_factor": {
                    "type": "boolean"
                },
                "uf": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "verification_seal": {
                    "type": "boolean"
                },
                "years_experience": {
                    "type": "integer"
                }
            }
        },
        "model.User": {
            "type": "object",
            "required": [
                "address",
                "cep",
                "city",
                "cpf",
                "email",
                "name",
                "neighborhood",
                "number",
                "password",
                "phone",
                "role",
                "street",
                "uf"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "cep": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "complement": {
                    "type": "string"
                },
                "cpf": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_access": {
                    "type": "boolean"
                },
                "gatewayCustomerID": {
                    "type": "string"
                },
                "hidden": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "neighborhood": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "profile_image_id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "temp_code": {
                    "type": "integer"
                },
                "two_factor": {
                    "type": "boolean"
                },
                "uf": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "utils.AuthUserResponse": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "profile_image_id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "two_factor": {
                    "type": "boolean"
                }
            }
        },
        "utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Descrição do erro"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "utils.SuccessConversationsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Reutilizável para Nurse e Patient",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ConversationDTO"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Lista de conversas retornada com sucesso"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessDashboardResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.DashboardAdminDataResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Dados de dashboard carregados com sucesso"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessDocumentsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Note que é um slice []",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DocumentInfoResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Documentos retornados com sucesso"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessMessagesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Message"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Histórico de mensagens retornado com sucesso"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessResponseNoData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operação realizada com sucesso"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessResponseNurse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Aponta para a struct real do enfermeiro",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Nurse"
                        }
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "Cadastro de enfermeiro solicitado com sucesso."
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessResponseString": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "Mensagem de dados"
                },
                "message": {
                    "type": "string",
                    "example": "Operação realizada com sucesso"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessUserListsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UserListsResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Listas de usuários retornadas com sucesso."
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessUserTypeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UserTypeResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Usuário atualizado com sucesso."
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessValidateCodeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/utils.ValidateCodeResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Código validado com sucesso"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.SuccessVisitTypeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.VisitTypeResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Visita atualizada com sucesso."
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "utils.ValidateCodeResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/utils.AuthUserResponse"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "\"Para autorizar, insira seu token JWT precedido de 'Bearer '. Exemplo: Bearer \u003cseu-token-aqui\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Vita API doc",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
