// Code generated by MockGen. DO NOT EDIT.
// Source: internal/admin/adminService.go
//
// Generated by this command:
//
//	mockgen -source=internal/admin/adminService.go -destination=internal/admin/mocks/mock_adminService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "medassist/internal/admin/dto"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gridfs "go.mongodb.org/mongo-driver/mongo/gridfs"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminService is a mock of AdminService interface.
type MockAdminService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminServiceMockRecorder
	isgomock struct{}
}

// MockAdminServiceMockRecorder is the mock recorder for MockAdminService.
type MockAdminServiceMockRecorder struct {
	mock *MockAdminService
}

// NewMockAdminService creates a new mock instance.
func NewMockAdminService(ctrl *gomock.Controller) *MockAdminService {
	mock := &MockAdminService{ctrl: ctrl}
	mock.recorder = &MockAdminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminService) EXPECT() *MockAdminServiceMockRecorder {
	return m.recorder
}

// ApproveNurseRegister mocks base method.
func (m *MockAdminService) ApproveNurseRegister(approvedUserId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveNurseRegister", approvedUserId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveNurseRegister indicates an expected call of ApproveNurseRegister.
func (mr *MockAdminServiceMockRecorder) ApproveNurseRegister(approvedUserId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveNurseRegister", reflect.TypeOf((*MockAdminService)(nil).ApproveNurseRegister), approvedUserId)
}

// DeleteNurseOrUser mocks base method.
func (m *MockAdminService) DeleteNurseOrUser(userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNurseOrUser", userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNurseOrUser indicates an expected call of DeleteNurseOrUser.
func (mr *MockAdminServiceMockRecorder) DeleteNurseOrUser(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNurseOrUser", reflect.TypeOf((*MockAdminService)(nil).DeleteNurseOrUser), userId)
}

// DeleteVisit mocks base method.
func (m *MockAdminService) DeleteVisit(visitId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVisit", visitId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVisit indicates an expected call of DeleteVisit.
func (mr *MockAdminServiceMockRecorder) DeleteVisit(visitId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVisit", reflect.TypeOf((*MockAdminService)(nil).DeleteVisit), visitId)
}

// GetDashboardData mocks base method.
func (m *MockAdminService) GetDashboardData() (dto.DashboardAdminDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardData")
	ret0, _ := ret[0].(dto.DashboardAdminDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardData indicates an expected call of GetDashboardData.
func (mr *MockAdminServiceMockRecorder) GetDashboardData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardData", reflect.TypeOf((*MockAdminService)(nil).GetDashboardData))
}

// GetFileStream mocks base method.
func (m *MockAdminService) GetFileStream(fileID primitive.ObjectID) (*gridfs.DownloadStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileStream", fileID)
	ret0, _ := ret[0].(*gridfs.DownloadStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileStream indicates an expected call of GetFileStream.
func (mr *MockAdminServiceMockRecorder) GetFileStream(fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileStream", reflect.TypeOf((*MockAdminService)(nil).GetFileStream), fileID)
}

// GetNurseDocumentsToAnalisys mocks base method.
func (m *MockAdminService) GetNurseDocumentsToAnalisys(nurseID string) ([]dto.DocumentInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNurseDocumentsToAnalisys", nurseID)
	ret0, _ := ret[0].([]dto.DocumentInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNurseDocumentsToAnalisys indicates an expected call of GetNurseDocumentsToAnalisys.
func (mr *MockAdminServiceMockRecorder) GetNurseDocumentsToAnalisys(nurseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNurseDocumentsToAnalisys", reflect.TypeOf((*MockAdminService)(nil).GetNurseDocumentsToAnalisys), nurseID)
}

// RejectNurseRegister mocks base method.
func (m *MockAdminService) RejectNurseRegister(rejectedNurseId string, rejectDescription dto.RejectDescription) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectNurseRegister", rejectedNurseId, rejectDescription)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RejectNurseRegister indicates an expected call of RejectNurseRegister.
func (mr *MockAdminServiceMockRecorder) RejectNurseRegister(rejectedNurseId, rejectDescription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectNurseRegister", reflect.TypeOf((*MockAdminService)(nil).RejectNurseRegister), rejectedNurseId, rejectDescription)
}

// UpdateUser mocks base method.
func (m *MockAdminService) UpdateUser(userId string, updates map[string]any) (dto.UserTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", userId, updates)
	ret0, _ := ret[0].(dto.UserTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockAdminServiceMockRecorder) UpdateUser(userId, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockAdminService)(nil).UpdateUser), userId, updates)
}

// UpdateVisit mocks base method.
func (m *MockAdminService) UpdateVisit(visitId string, updates map[string]any) (dto.VisitTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVisit", visitId, updates)
	ret0, _ := ret[0].(dto.VisitTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVisit indicates an expected call of UpdateVisit.
func (mr *MockAdminServiceMockRecorder) UpdateVisit(visitId, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVisit", reflect.TypeOf((*MockAdminService)(nil).UpdateVisit), visitId, updates)
}

// UserLists mocks base method.
func (m *MockAdminService) UserLists() (dto.UserListsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLists")
	ret0, _ := ret[0].(dto.UserListsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserLists indicates an expected call of UserLists.
func (mr *MockAdminServiceMockRecorder) UserLists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLists", reflect.TypeOf((*MockAdminService)(nil).UserLists))
}
